### ISSUE TITLE
about [go-first-course][35][workerpool2] returnTask method 

### ISSUE THREAD

**Issue by setdaemon** [bigwhite/publication#1]
你好，最近刚入门go，在看您的课程，关于这一节课的代码有个疑问：
如果没有理解错的话，publication/tree/master/column/timegeek/go-first-course/35/workerpool2/pool.go从第108行开始的for range逻辑中，意图是从p.task的通道里获取task信号，根据这个信号创建worker，并通过returnTask方法再次向tasks的管道中发送信号，目的是让刚刚新产生的worker能够接收到task任务并执行任务？
但是这里我有个疑问，假设现在我们只创建出了一个worker协程，那此时就有两个协程在监听tasks通道，那returnTask中回写的信息没办法确定一定会被worker协程接收到吧？（我理解returnTask本意是希望worker协程收到这个信号并执行task）这样导致的一个结果可能是Schedule了一个task，但是创建出了不止一个worker出来，测试的时候一般会创建出来2~3个worker。
我理解这里是不是应该添加一个task至多只创建出一个worker出来才对？

**Comment by bigwhite** [comment]
在preAlloc=false的情况下，在pool池尚未满的情况下，task的确被当做信号用了。考虑到调度的不确定性，你说的情况是存在的。

**Comment by bigwhite** [comment]
同样也可能存在schedule task后不创建worker的情况，因为被已有的worker给消费了。当然这是在已经创建了一些worker的情况下。
